# Site settings
title: 周庆奕的个人主页
url: "https://zqygg.github.io"

# Author
author:
  name: 周庆奕
  desc: Hello nice to meet you
  email: zqygg@mail.ustc.edu.cn
  selfie: assets/img/profile.jpg

a {
color: red;
}

a:link {
color: blue;
}
a:hover {
color: red;
}

# social
social:
  email: true
  behance:
  bitbucket:
  dribbble:
  facebook: 
  bilibili: https://space.bilibili.com/1332829244
  flickr:
  github: zqygg
  google_plus:
  instagram:
  keybase:
  linkedin: 
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:
  steam: 76561198423560965
  tumblr:
  gitlab:
  twitter: 
  vimeo:
  wordpress:
  youtube:
  default_txt: "Follow On"

# Build settings
markdown: kramdown

# Assets
sass:
  sass_dir: _sass
  style: compressed

# Gems
plugins:
  - jekyll-paginate

# Permalinks
permalink: /:year-:month-:day/:title
paginate_path: "/portfolio/page:num/"
paginate: 5
exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "*.gem"
  - "LICENSE"
  - "READE.md"
  - "screenshot.png"
